from pydantic import BaseModel, Field, field_validator, ValidationError as PydanticValidationError
from typing import List, Optional, Dict, Any
from .validators import validate_price, validate_quantity, validate_minimum_stock_level, validate_generate_quantity
from .exceptions import ValidationError


class GeneratedProductSchema(BaseModel):
    name: str = Field(..., min_length=1, description="Product name")
    price: float = Field(..., gt=0.0, description="Product price")
    quantity: int = Field(..., ge=0, description="Stock quantity")
    description: str = Field(default="", description="Product description")
    barcode: Optional[str] = Field(default=None, description="Product barcode")
    category: str = Field(default="", description="Comma-separated category names")
    brand: str = Field(default="", description="Product brand")
    minimum_stock_level: int = Field(default=0, ge=0, description="Minimum stock level")

    @field_validator('name')
    @classmethod
    def validate_name(cls, v: str) -> str:
        if isinstance(v, str):
            v = v.strip()
        return v

    @field_validator('price')
    @classmethod
    def validate_price_field(cls, v: float) -> float:
        return float(validate_price(v))

    @field_validator('quantity')
    @classmethod
    def validate_quantity_field(cls, v: int) -> int:
        return validate_quantity(v)

    @field_validator('minimum_stock_level')
    @classmethod
    def validate_minimum_stock_level_field(cls, v: int) -> int:
        return validate_minimum_stock_level(v)

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class GeneratedProductListSchema(BaseModel):
    products: List[GeneratedProductSchema]

    class Config:
        validate_assignment = True


class TextGenerationRequestSchema(BaseModel):
    prompt: str = Field(..., min_length=1, description="Generation prompt")
    temperature: Optional[float] = Field(None, ge=0.0, le=2.0)
    max_output_tokens: Optional[int] = Field(None, gt=0)
    top_p: Optional[float] = Field(None, ge=0.0, le=1.0)
    top_k: Optional[int] = Field(None, gt=0)
    top_sequences: Optional[int] = Field(None, gt=0)

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class ProductGenerationRequestSchema(BaseModel):
    quantity: int = Field(..., ge=1, le=50, description="Number of products to generate")
    category: Optional[str] = Field(None, description="Comma-separated category names")

    @field_validator('quantity')
    @classmethod
    def validate_quantity_field(cls, v: int) -> int:
        return validate_generate_quantity(v)

    class Config:
        validate_assignment = True


class RetrieveRelevantChunksRequestSchema(BaseModel):
    query: str = Field(..., min_length=1, description="User query for retrieval")
    top_k: int = Field(default=3, ge=1, le=20, description="Number of chunks to retrieve")
    include_product_context: bool = Field(default=True, description="Whether to include product retrieval context")
    category: Optional[str] = Field(None, description="Optional category filter")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class RetrievedChunkSchema(BaseModel):
    source_id: str = Field(..., min_length=1, description="Stable source document identifier")
    source_name: str = Field(..., min_length=1, description="Human-readable source name")
    chunk_id: str = Field(..., min_length=1, description="Chunk identifier inside source")
    content: str = Field(..., min_length=1, description="Retrieved chunk text")
    score: float = Field(..., description="Vector similarity score")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional retrieval metadata")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class AskExpertRequestSchema(BaseModel):
    query: str = Field(..., min_length=1, description="User question for RAG answer")
    top_k: int = Field(default=3, ge=1, le=20, description="Number of chunks to use as context")
    include_product_context: bool = Field(default=True, description="Whether to include product retrieval context")
    category: Optional[str] = Field(None, description="Optional category filter")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class AskExpertResponseSchema(BaseModel):
    answer: str = Field(..., min_length=1, description="Grounded answer generated by RAG")
    sources: List[RetrievedChunkSchema] = Field(default_factory=list, description="Cited retrieved chunks")
    token_usage: Optional[Dict[str, int]] = Field(default=None, description="Optional model token accounting")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Optional response metadata")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class QuoteAgentRequestSchema(BaseModel):
    query: str = Field(..., min_length=1, description="Natural language quote request")
    quantity: Optional[int] = Field(default=None, ge=1, description="Optional explicit quantity override")
    top_k: int = Field(default=5, ge=1, le=20, description="Candidate products to consider during identification")
    category: Optional[str] = Field(default=None, description="Optional category filter for product identification")
    score_threshold: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Optional vector similarity score threshold")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class QuoteIdentifiedProductSchema(BaseModel):
    id: str = Field(..., min_length=1, description="Identified product ID")
    name: str = Field(..., min_length=1, description="Identified product name")
    category: str = Field(default="", description="Product category")
    brand: str = Field(default="", description="Product brand")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class QuoteInventoryStatusSchema(BaseModel):
    quantity_available: int = Field(..., ge=0, description="Current inventory quantity")
    minimum_stock_level: int = Field(..., ge=0, description="Configured minimum stock threshold")
    in_stock: bool = Field(..., description="Whether any stock is currently available")
    low_stock: bool = Field(..., description="Whether stock is at or below minimum threshold")
    can_fulfill: bool = Field(..., description="Whether inventory can fulfill the requested quantity")

    class Config:
        validate_assignment = True


class QuoteDiscountSchema(BaseModel):
    tier_name: str = Field(..., min_length=1, description="Applied discount tier name")
    discount_percent: float = Field(..., ge=0.0, le=100.0, description="Applied discount percent")
    discount_amount: float = Field(..., ge=0.0, description="Discount amount in currency units")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class QuoteLineItemSchema(BaseModel):
    product_id: str = Field(..., min_length=1, description="Quoted product ID")
    product_name: str = Field(..., min_length=1, description="Quoted product name")
    unit_price: float = Field(..., ge=0.0, description="Price per unit")
    quantity: int = Field(..., ge=1, description="Requested quantity")
    subtotal: float = Field(..., ge=0.0, description="Subtotal before discounts")
    final_total: float = Field(..., ge=0.0, description="Final total after discount")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class QuoteCandidateSchema(BaseModel):
    identified_product: QuoteIdentifiedProductSchema = Field(..., description="Candidate product")
    inventory: Optional[QuoteInventoryStatusSchema] = Field(
        default=None,
        description="Inventory status for candidate product",
    )
    discount: Optional[QuoteDiscountSchema] = Field(
        default=None,
        description="Discount details for candidate product",
    )
    quote: Optional[QuoteLineItemSchema] = Field(
        default=None,
        description="Quote line item for candidate product",
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Candidate metadata")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


class QuoteAgentResponseSchema(BaseModel):
    request: str = Field(..., min_length=1, description="Original user quote request")
    identified_product: QuoteIdentifiedProductSchema = Field(..., description="Product selected by the agent")

    # --- KEY CHANGE ---
    # inventory is Optional because the dynamic agent only fetches it when the
    # query actually asks about stock/availability. Queries like "give me all
    # details about product id X" never call check_inventory, so this field
    # must be allowed to be None in the response schema.
    inventory: Optional[QuoteInventoryStatusSchema] = Field(
        default=None,
        description="Current inventory status for selected product (None when not requested)",
    )

    discount: Optional[QuoteDiscountSchema] = Field(default=None, description="Applied discount details")
    quote: Optional[QuoteLineItemSchema] = Field(default=None, description="Final quote line item")
    summary: str = Field(..., min_length=1, description="Human-readable summary of the response")
    candidates: List[QuoteCandidateSchema] = Field(
        default_factory=list,
        description="Candidate quotes when selection is ambiguous",
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Agent metadata for diagnostics")

    class Config:
        validate_assignment = True
        str_strip_whitespace = True


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def validate_text_gen(request_data: Dict[str, Any]) -> TextGenerationRequestSchema:
    try:
        return TextGenerationRequestSchema(**request_data)
    except PydanticValidationError as e:
        raise ValidationError(f"Invalid text generation request: {str(e)}")


def validate_product_gen(request_data: Dict[str, Any]) -> ProductGenerationRequestSchema:
    try:
        return ProductGenerationRequestSchema(**request_data)
    except PydanticValidationError as e:
        raise ValidationError(f"Invalid product generation request: {str(e)}")


def validate_retrieve_chunks_request(request_data: Dict[str, Any]) -> RetrieveRelevantChunksRequestSchema:
    try:
        return RetrieveRelevantChunksRequestSchema(**request_data)
    except PydanticValidationError as e:
        raise ValidationError(f"Invalid retrieval request: {str(e)}")


def validate_ask_expert_request(request_data: Dict[str, Any]) -> AskExpertRequestSchema:
    try:
        return AskExpertRequestSchema(**request_data)
    except PydanticValidationError as e:
        raise ValidationError(f"Invalid ask-expert request: {str(e)}")


def validate_ask_expert_response(response_data: Dict[str, Any]) -> AskExpertResponseSchema:
    try:
        return AskExpertResponseSchema(**response_data)
    except PydanticValidationError as e:
        raise ValidationError(f"Invalid ask-expert response: {str(e)}")


def validate_quote_agent_request(request_data: Dict[str, Any]) -> QuoteAgentRequestSchema:
    try:
        return QuoteAgentRequestSchema(**request_data)
    except PydanticValidationError as e:
        raise ValidationError(f"Invalid quote-agent request: {str(e)}")


def validate_quote_agent_response(response_data: Dict[str, Any]) -> QuoteAgentResponseSchema:
    try:
        return QuoteAgentResponseSchema(**response_data)
    except PydanticValidationError as e:
        raise ValidationError(f"Invalid quote-agent response: {str(e)}")


def extract_config(request: TextGenerationRequestSchema) -> Dict[str, Any]:
    config = {}
    optional_fields = [
        "temperature",
        "max_output_tokens",
        "top_p",
        "top_k",
        "top_sequences",
    ]
    for field in optional_fields:
        value = getattr(request, field, None)
        if value is not None:
            config[field] = value
    return config


def validate_products_schema(
    products_data: List[Dict[str, Any]], logger: Any = None
) -> List[GeneratedProductSchema]:
    validated_products: List[GeneratedProductSchema] = []

    for idx, product_data in enumerate(products_data):
        try:
            validated_product = GeneratedProductSchema(**product_data)
            validated_products.append(validated_product)
        except PydanticValidationError as e:
            if logger:
                logger.warning(
                    f"Product at index {idx} failed validation",
                    product_data=product_data,
                    error=str(e),
                )

    if not validated_products:
        raise ValidationError("Failed to validate any products from AI response")

    if len(validated_products) < len(products_data) and logger:
        logger.warning(
            "Some products were skipped due to validation errors",
            total=len(products_data),
            valid=len(validated_products),
        )

    return validated_products